config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :books do
    member do
      get :new_borrow
      patch :borrow
      get :new_return
      # patch :return
    end
  end

   root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user, optional: true

  validates :title, presence: { message: "O título é obrigatório!" }
  validates :author, presence: { message: "O autor é obrigatório!" }

  def available?
    status == "disponível"
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: { message: "O Nome é obrigatório!" }
  validates :email, presence: true, format: {
    with: URI::MailTo::EMAIL_REGEXP,
    message: "não é um email válido"
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path, notice: "Livro cadastrado com sucesso!"
    else
      flash[:alert] = "Erro ao cadastrar livro."
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to books_path, notice: "Livro atualizado com sucesso!"
    else
      flash[:alert] = "Erro ao atualizar livro."
      render :edit
    end
  end

  def new_borrow
    @book = Book.find(params[:id])
  end

  def borrow
    @book = Book.find(params[:id])
    user = User.find(params[:user_id])

    if @book.status == "disponível" && @book.update(status: "emprestado", user_id: user.id)
      redirect_to books_path, notice: "O livro '#{@book.title}' foi emprestado para #{user.name}."
    else
      redirect_to books_path, alert: "Não foi possível emprestar o livro '#{@book.title}'."
    end
  end

  def new_return
    @book = Book.find(params[:id])
    give_back
  end

  def give_back
    @book = Book.find(params[:id])
    if @book.status == "emprestado"
      @book.update(status: "disponível", user_id: nil)

      redirect_to books_path, notice: "O livro '#{@book.title}' foi devolvido com sucesso."
    else
      redirect_to books_path, alert: "Este livro não está emprestado."
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :status)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path, notice: "Usuário cadastrado com sucesso!"
    else
      flash[:alert] = "Erro ao cadastrar usuário."
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path, notice: "Usuário atualizado com sucesso!"
    else
      flash[:alert] =  "Erro ao atualizar usuário."
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model: @book, local: true do |form| %>
   <hr>
  <div class="mb-3">
    <%= form.label :title, 'Título', "class": 'form-label' %>
    <%= form.text_field :title, required: true, "class": 'form-control', "style": 'width: 400px' %>
  </div>

  <div class="mb-3">
    <%= form.label :author, 'Autor', "class": 'form-label' %>
    <%= form.text_field :author, required: true, "class": 'form-control', "style": 'width: 400px' %>
  </div>

  <div class="mb-3">
    <%= form.label :status, 'Status', "class": 'form-label' %>
    <br>
    <%= form.select :status, [['Disponível', 'disponível'], ['Emprestado', 'emprestado']] %>
  </div>

  <br>
  <div>
    <%= form.submit action_name == 'new' ? 'Cadastrar' : 'Atualizar' %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editar Livro</h1>
<%= render 'form' %>

app/views/books/index.html.erb
<h1>Livros</h1>
<%= link_to 'Novo Livro', new_book_path, "class": 'btn btn-primary' %>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Título</th>
        <th scope="col">Autor</th>
        <th scope="col">Status</th>
        <th scope="col" style="text-align: center;">Ações</th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= book.id %></td>
          <td><%= book.title %></td>
          <td><%= book.author %></td>
          <td><%= book.status %></td>
          <td style="text-align: center;">
              <% if book.status == 'disponível' %>
                <%= link_to 'Editar', edit_book_path(book), "class": "btn btn-primary" %>
                | <%= link_to 'Emprestar', new_borrow_book_path(book), "class": "btn btn-secondary" %>
              <% else %>
                <% if book.user.present? %>
                  | Emprestado para <%= book.user.name %>
                  | <%= link_to 'Devolver', new_return_book_path(book), method: :patch, "class": "btn btn-warning", data: { confirm: 'Tem certeza que deseja devolver o livro?' } %>
                <% else %>
                  Livro fora do estoque! Consulte o atendente!
                  <%= link_to 'Editar', edit_book_path(book), "class": "btn btn-primary" %>
                <% end %>
              <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/books/new.html.erb
<h1>Cadastrar Livro</h1>
<%= render 'form' %>

app/views/books/new_borrow.html.erb
<h1>Emprestar Livro</h1>
<hr>
<p style="font-size: 20px; font-weight: 500;">Selecione o usuário para quem deseja emprestar o livro "<%= @book.title %>":</p>

<%= form_with url: borrow_book_path(@book), method: :patch, local: true do |form| %>
  <div>
    <%= form.label :user_id, 'Usuário', "class": 'form-label' %>
    <br>
    <%= form.collection_select :user_id, User.all, :id, :name, prompt: 'Selecione um usuário' %>
  </div>
  <br>
  <div>
    <%= form.submit 'Emprestar', "class": 'btn btn-primary' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Biblioteca" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Biblioteca</a>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="/">Usuários</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/books">Livros</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with model: @user, local: true do |form| %>
  <hr>
  <div class="mb-3">
    <%= form.label :name, 'Nome', "class": 'form-label' %>
    <%= form.text_field :name, required: true, "class": 'form-control', "style": 'width: 400px' %>
  </div>

  <div class="mb-3">
    <%= form.label :email, 'Email', "class": 'form-label' %>
    <%= form.email_field :email, required: true, "class": 'form-control', "style": 'width: 400px' %>
  </div>
  <br>
  <div>
    <%= form.submit action_name == 'new' ? 'Cadastrar' : 'Atualizar', "class": 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editar Usuário</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1>Usuários</h1>
<%= link_to 'Novo Usuário', new_user_path, "class": 'btn btn-primary' %>
<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Nome</th>
      <th>Email</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td>
          <%= link_to 'Editar', edit_user_path(user), "class": 'btn btn-primary' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>Cadastrar Usuário</h1>
<%= render 'form' %>